# Generated by Django 3.2.9 on 2021-11-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=255)),
                ('album_artist', models.CharField(max_length=255)),
                ('album_labels', models.CharField(blank=True, max_length=255, null=True)),
                ('album_tracks', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
